name: AugmentedReality
favicon: null
layout_spectrum: 0.7380390767939389
typography_spectrum: 0.22485550353303552
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9540767988655716
  lightness: 0.8028981091920286
  saturation: 0.41948663373477757
  rhythmicContrast: 0.37040264206007123
purpose: []
